name: car_rental_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  path: any
  async: any
  cupertino_icons: ^1.0.5
  rxdart: ^0.27.7
  flutter_offline: ^3.0.1
  web: 0.5.0
  flutter_plugin_android_lifecycle: 2.0.16
  connectivity_plus: 5.0.2
  network_info_plus: 4.1.0
  global_configs: ^1.1.2
  http: ^1.2.0
  http_interceptor: ^2.0.0-beta.8
  intl: ^0.18.1
  openapi_generator: ^5.0.2
  sqflite: 2.3.2
  uuid:
  pluto_grid: ^7.0.2
  get_it: ^7.6.7
  provider: ^6.1.1
  go_router: ^13.0.1
  flutter_svg: ^2.0.9
  flutter_file_saver: ^0.6.2
  universal_html: ^2.2.3
  flutter_form_builder: ^9.2.0
  form_builder_file_picker: ^4.0.0
  get: ^4.6.6
  logging: ^1.2.0
  url_strategy: ^0.2.0
  flutter_dotenv: ^5.1.0
  carousel_slider: ^4.2.1
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  flutter_data_table: ^1.1.2

dev_dependencies:
  flutter_lints: ^3.0.1
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: Trajan
      fonts:
        - asset: assets/fonts/TrajanPro.ttf
        - asset: assets/fonts/TrajanPro-Bold.ttf